name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9
    
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pylint
                pip install -r requirements.txt -r requirements-dev.txt
    
          - name: Run Pylint
            run: pylint eaip_parser  # Replace "your_module_or_package" with the correct module or package name
    
          - name: Run pytest
            run: pytest --cov=eaip_parser
    release:
        runs-on: ubuntu-latest
        needs: lint-and-test
        concurrency: release
        permissions:
            id-token: write
            contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Python Semantic Release
              uses: python-semantic-release/python-semantic-release@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
